config/routes.rb
Rails.application.routes.draw do
  resources :anuncios

  root 'welcome#index'

end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  validates :nombre_mascota,  presence: true,
                              length: { minimum: 2 }
  validates :nombre_cuidador,  presence: true,
                              length: { minimum: 2 }
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController

def index
  @anuncios = Anuncio.all
end

def show
  @anuncio = Anuncio.find(params[:id])
end

def new
  @anuncio = Anuncio.new
end

def edit
  @anuncio = Anuncio.find(params[:id])
end

def create
  @anuncio = Anuncio.new(anuncio_params)

  if @anuncio.save
    redirect_to @anuncio
  else
    render 'new'
  end
end

def update
  @anuncio = Anuncio.find(params[:id])

  if @anuncio.update(anuncio_params)
    redirect_to @anuncio
  else
    render 'edit'
  end
end

def destroy
  @anuncio = Anuncio.find(params[:id])
  @anuncio.destroy

  redirect_to anuncios_path
end

private
  def anuncio_params
    params.require(:anuncio).permit(:nombre_mascota, :descripcion, :nombre_cuidador)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/anuncios/_form.html.erb
<%= form_for @anuncio do |f| %>

  <% if @anuncio.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@anuncio.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @anuncio.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :nombre_mascota %><br>
    <%= f.text_field :nombre_mascota %>
  </p>

  <p>
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </p>

  <p>
    <%= f.label :nombre_cuidador %><br>
    <%= f.text_field :nombre_cuidador %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/anuncios/edit.html.erb
<h1>Editando el anuncio</h1>

<%= render 'form' %>

<%= link_to 'Volver', anuncios_path %>

app/views/anuncios/index.html.erb
<h1>Listado de Anuncios</h1>

<%= link_to 'Nuevo Anuncio', new_anuncio_path %>

<table>
  <tr>
    <th>Nombre Mascota</th>
    <th>Descripcion</th>
    <th>Nombre Cuidador</th>
    <th colspan="3"></th>
  </tr>

  <% @anuncios.each do |anuncio| %>
    <tr>
      <td><%= anuncio.nombre_mascota %></td>
      <td><%= anuncio.descripcion %></td>
      <td><%= anuncio.nombre_cuidador %></td>
      <td><%= link_to 'Ver', anuncio_path(anuncio) %></td>
      <td><%= link_to 'Editar', edit_anuncio_path(anuncio) %></td>
      <td><%= link_to 'Eliminar', anuncio_path(anuncio),
              method: :delete,
              data: { confirm: 'Estas seguro?' } %></td>
    </tr>
  <% end %>
</table>

app/views/anuncios/new.html.erb
<h1>Nuevo Anuncio</h1>

<%= render 'form' %>

<%= link_to 'Volver', anuncios_path %>

app/views/anuncios/show.html.erb
<p>
  <strong>Nombre Mascota:</strong>
  <%= @anuncio.nombre_mascota %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @anuncio.descripcion %>
</p>

<p>
  <strong>Nombre Cuidador:</strong>
  <%= @anuncio.nombre_cuidador %>
</p>

<%= link_to 'Editar', edit_anuncio_path(@anuncio) %>
<%= link_to 'Volver', anuncios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anuncios</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Bienvenido</h1>
<h3>Por favor, seleccione el link que desea</h3>
<%= link_to 'Anuncios de mascotas perdidas', controller: 'anuncios' %>